/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Chat
 */
export interface Chat {

    /**
     * @type {string}
     * @memberof Chat
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Chat
     */
    projectId?: string;

    /**
     * @type {string}
     * @memberof Chat
     */
    sender?: string;

    /**
     * @type {string}
     * @memberof Chat
     */
    receiver?: string;

    /**
     * @type {string}
     * @memberof Chat
     */
    mode?: ChatModeEnum;

    /**
     * @type {Date}
     * @memberof Chat
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof Chat
     */
    updatedAt?: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum ChatModeEnum {
    OFF = 'OFF',
    LISTEN = 'LISTEN',
    ON = 'ON'
}

