/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { ChatbotAttachement } from './chatbot-attachement';
 /**
 * 
 *
 * @export
 * @interface Chatbot
 */
export interface Chatbot {

    /**
     * @type {string}
     * @memberof Chatbot
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Chatbot
     */
    label?: string;

    /**
     * @type {string}
     * @memberof Chatbot
     */
    prompt?: string;

    /**
     * @type {string}
     * @memberof Chatbot
     */
    description?: string;

    /**
     * @type {string}
     * @memberof Chatbot
     */
    projectId?: string;

    /**
     * @type {string}
     * @memberof Chatbot
     */
    languageModel?: ChatbotLanguageModelEnum;

    /**
     * @type {string}
     * @memberof Chatbot
     */
    accessKey?: string;

    /**
     * @type {Array<ChatbotAttachement>}
     * @memberof Chatbot
     */
    chatbotAttachements?: Array<ChatbotAttachement>;

    /**
     * @type {Date}
     * @memberof Chatbot
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof Chatbot
     */
    updatedAt?: Date;
}

/**
 * @export
 * @enum {string}
 */
export enum ChatbotLanguageModelEnum {
    MISTRAL = 'MISTRAL',
    GEMINI = 'GEMINI'
}

