/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateUserDto
 */
export interface CreateUserDto {

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    projectId: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    externalId: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    avatar?: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    displayName: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    email?: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    phoneNumber?: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    login: string;

    /**
     * @type {string}
     * @memberof CreateUserDto
     */
    secret: string;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof CreateUserDto
     */
    customJson?: { [key: string]: string; };
}
