/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface CreateChatbotDto
 */
export interface CreateChatbotDto {

    /**
     * @type {string}
     * @memberof CreateChatbotDto
     */
    label: string;

    /**
     * @type {string}
     * @memberof CreateChatbotDto
     */
    prompt: string;

    /**
     * @type {string}
     * @memberof CreateChatbotDto
     */
    projectId: string;

    /**
     * @type {string}
     * @memberof CreateChatbotDto
     */
    description?: string;

    /**
     * @type {string}
     * @memberof CreateChatbotDto
     */
    languageModel: CreateChatbotDtoLanguageModelEnum;

    /**
     * @type {Array<Blob>}
     * @memberof CreateChatbotDto
     */
    attachements?: Array<Blob>;
}

/**
 * @export
 * @enum {string}
 */
export enum CreateChatbotDtoLanguageModelEnum {
    MISTRAL = 'MISTRAL',
    GEMINI = 'GEMINI'
}

