/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { MessageAttachement } from './message-attachement';
 /**
 * 
 *
 * @export
 * @interface Message
 */
export interface Message {

    /**
     * @type {string}
     * @memberof Message
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Message
     */
    projectId?: string;

    /**
     * @type {string}
     * @memberof Message
     */
    body?: string;

    /**
     * @type {string}
     * @memberof Message
     */
    ack?: MessageAckEnum;

    /**
     * @type {string}
     * @memberof Message
     */
    sender?: string;

    /**
     * @type {string}
     * @memberof Message
     */
    receiver?: string;

    /**
     * @type {Array<MessageAttachement>}
     * @memberof Message
     */
    messageAttachements?: Array<MessageAttachement>;

    /**
     * @type {Date}
     * @memberof Message
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof Message
     */
    updatedAt?: Date;

    /**
     * @type {boolean}
     * @memberof Message
     */
    writtenByHuman?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum MessageAckEnum {
    SENT = 'SENT',
    RECEIVED = 'RECEIVED',
    READ = 'READ'
}

