/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface MessageAttachement
 */
export interface MessageAttachement {

    /**
     * @type {string}
     * @memberof MessageAttachement
     */
    id?: string;

    /**
     * @type {string}
     * @memberof MessageAttachement
     */
    mimetype?: string;

    /**
     * @type {string}
     * @memberof MessageAttachement
     */
    filename?: string;

    /**
     * @type {number}
     * @memberof MessageAttachement
     */
    filesize?: number;

    /**
     * @type {Date}
     * @memberof MessageAttachement
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof MessageAttachement
     */
    updatedAt?: Date;

    /**
     * @type {string}
     * @memberof MessageAttachement
     */
    path?: string;
}
