/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Chatbot } from './chatbot';
 /**
 * 
 *
 * @export
 * @interface Organization
 */
export interface Organization {

    /**
     * @type {string}
     * @memberof Organization
     */
    id?: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    name?: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    email?: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    projectId?: string;

    /**
     * @type {string}
     * @memberof Organization
     */
    privateKey?: string;

    /**
     * @type {Array<Chatbot>}
     * @memberof Organization
     */
    chatbots?: Array<Chatbot>;

    /**
     * @type {Date}
     * @memberof Organization
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof Organization
     */
    updatedAt?: Date;

    /**
     * @type {string}
     * @memberof Organization
     */
    username?: string;

    /**
     * @type {boolean}
     * @memberof Organization
     */
    enabled?: boolean;

    /**
     * @type {boolean}
     * @memberof Organization
     */
    accountNonExpired?: boolean;

    /**
     * @type {boolean}
     * @memberof Organization
     */
    accountNonLocked?: boolean;

    /**
     * @type {boolean}
     * @memberof Organization
     */
    credentialsNonExpired?: boolean;
}
