/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Organization } from './organization';
import { User } from './user';
 /**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {string}
     * @memberof User
     */
    id?: string;

    /**
     * @type {string}
     * @memberof User
     */
    projectId?: string;

    /**
     * @type {string}
     * @memberof User
     */
    externalId?: string;

    /**
     * @type {string}
     * @memberof User
     */
    avatar?: string;

    /**
     * @type {string}
     * @memberof User
     */
    displayName?: string;

    /**
     * @type {string}
     * @memberof User
     */
    email?: string;

    /**
     * @type {string}
     * @memberof User
     */
    phoneNumber?: string;

    /**
     * @type {string}
     * @memberof User
     */
    login?: string;

    /**
     * @type {{ [key: string]: string; }}
     * @memberof User
     */
    customJson?: { [key: string]: string; };

    /**
     * @type {Array<User>}
     * @memberof User
     */
    contacts?: Array<User>;

    /**
     * @type {Organization}
     * @memberof User
     */
    organization?: Organization;

    /**
     * @type {Date}
     * @memberof User
     */
    createdAt?: Date;

    /**
     * @type {Date}
     * @memberof User
     */
    updatedAt?: Date;

    /**
     * @type {string}
     * @memberof User
     */
    username?: string;

    /**
     * @type {boolean}
     * @memberof User
     */
    online?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    enabled?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    accountNonExpired?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    accountNonLocked?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    credentialsNonExpired?: boolean;
}
