/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { PreKey } from './pre-key';
import { SignedPreKey } from './signed-pre-key';
 /**
 * 
 *
 * @export
 * @interface PreKeyBundle
 */
export interface PreKeyBundle {

    /**
     * @type {Array<string>}
     * @memberof PreKeyBundle
     */
    identityKey?: Array<string>;

    /**
     * @type {number}
     * @memberof PreKeyBundle
     */
    registrationId?: number;

    /**
     * @type {PreKey}
     * @memberof PreKeyBundle
     */
    preKey?: PreKey;

    /**
     * @type {SignedPreKey}
     * @memberof PreKeyBundle
     */
    signedPreKey?: SignedPreKey;
}
