/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface PreKey
 */
export interface PreKey {

    /**
     * @type {number}
     * @memberof PreKey
     */
    keyId?: number;

    /**
     * @type {Array<string>}
     * @memberof PreKey
     */
    publicKey?: Array<string>;
}
