/* tslint:disable */
/* eslint-disable */
/**
 * API Documentation
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface SendMessageDto
 */
export interface SendMessageDto {

    /**
     * @type {string}
     * @memberof SendMessageDto
     */
    senderId: string;

    /**
     * @type {string}
     * @memberof SendMessageDto
     */
    receiverId: string;

    /**
     * @type {string}
     * @memberof SendMessageDto
     */
    body: string;

    /**
     * @type {Array<Blob>}
     * @memberof SendMessageDto
     */
    attachements?: Array<Blob>;

    /**
     * @type {string}
     * @memberof SendMessageDto
     */
    projectId: string;
}
