import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro', // This refers to docs/intro.md
    'architecture_overview', // This refers to docs/architecture_overview.md
    'domain_layer', // This refers to docs/domain_layer.md
    'infrastructure_layer', // This refers to docs/infrastructure_layer.md
    'presentation_layer', // This refers to docs/presentation_layer.md
    // You can add more items here:
    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'], // Example if you have such files
    // },
  ],
};

export default sidebars;
